### ISSUE TITLE
Maybe too hard for humans

### ISSUE THREAD

**Issue by neoneye** [lalalune/arc-wfc-data#1]
Thanks for making a new ARC dataset. Your datasets is something I immediately checked out.

IMHO your dataset is a bit too difficult for humans to solve. Maybe it's not a good reference for what kind of puzzles humans are able to solve, and thus maybe not good training data.

I have tried solve around 10 puzzles. But I'm unable to solve most of them. I have solved 1 of them.

With identical structured input images. Then finding the output seems to be possible by taking one of the other output images and remap the colors, and rotation and flipping.

# Examples of puzzles
![Untitled 2](https://github.com/lalalune/arc-wfc-data/assets/147971/18154c92-ec33-4b39-9d7d-9413900c0245)
![Screenshot 2024-06-22 at 10 47 04](https://github.com/lalalune/arc-wfc-data/assets/147971/0ac375b4-ec11-4bd1-b253-933945b62863)

# Solutions

Input images with different sizes.

Augment the existing ARC tasks.

Use other ARC like datasets, such as RE-ARC, MiniARC, ConceptARC.

**Comment by lalalune** [comment]
Agreed. The kernels were too complicated, and the inputs should have been outputs and vice versa. I've updated and force pushed.

The goal of this specific dataset is to see if I can find programs or rules based on adjacency, similar to cellular automata, but with deterministic and collapsible rules. This is constrained to small patterns, but as long as the patterns can be extracted and learned, I think there is some hope for a kind of rule-finding algorithm that can be applied up to 30x30.

I was able to one shot this one with a simpler tile rule:
![Screenshot 2024-06-23 at 4 10 19 AM](https://github.com/lalalune/arc-wfc-data/assets/18633264/8f29a0d3-ee5a-4f73-804a-9126e14c11dc)
